# Generated by Django 5.1.2 on 2024-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confidence_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
