# Generated by Django 5.1.3 on 2024-12-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_conference_status'),
        ('reviews', '0002_review_confidence_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField()),
                ('has_comment', models.BooleanField()),
                ('has_score', models.BooleanField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateItem', to='conference.conference')),
            ],
        ),
    ]
