# Generated by Django 5.1.3 on 2024-12-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('reviews', '0003_reviewtemplateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsItem', to='papers.paper')),
                ('templateItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsItem', to='reviews.reviewtemplateitem')),
            ],
        ),
    ]
