# Generated by Django 5.1.2 on 2024-11-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='created_by',
            new_name='admin_id',
        ),
    ]
