# Generated by Django 4.2.16 on 2024-12-03 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_rename_created_by_conference_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='papers_deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
