# Generated by Django 5.1.2 on 2024-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_conference_papers_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='automatic_assign_status',
            field=models.BooleanField(default=False),
        ),
    ]
