# Generated by Django 5.1.3 on 2024-11-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0002_rename_created_by_conference_admin_id'),
        ('users', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paper_file', models.FileField(blank=True, null=True, upload_to='papers_pdf/')),
                ('status_id', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='users.user')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='conference.conference')),
            ],
        ),
    ]
