# Generated by Django 5.1.2 on 2024-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='preference',
            field=models.CharField(choices=[('not_interested', 'Not Interested'), ('interested', 'Interested')], max_length=20),
        ),
    ]
