# Generated by Django 5.1.2 on 2024-11-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0002_rename_created_by_conference_admin_id'),
        ('users', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], max_length=20)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_roles', to='conference.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_roles', to='users.user')),
            ],
        ),
    ]
